#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.

TOTAL_STAGES=5

banner "npm publish — @feather_wch/dsh-im"

# ── Stage 1: 发布前自检 ─────────────────────────────────────────────────
stage "1/5 · 发布前自检"
say "检查环境与包就绪状态（官方源 https://registry.npmjs.org）。"
say ""

# 1a) node / npm 版本
say "node $(node -v 2>/dev/null || echo '未找到'), npm $(npm -v 2>/dev/null || echo '未找到')"
say ""

# 1b) 定位包目录（支持从仓库根或 scripts/ 下运行）
PKG_DIR="."
if [[ ! -f "./package.json" ]]; then
  if [[ -f "../package.json" ]]; then PKG_DIR=".."
  elif [[ -f "$(dirname "$0")/../package.json" ]]; then PKG_DIR="$(dirname "$0")/.."
  fi
fi
if [[ ! -f "$PKG_DIR/package.json" ]]; then
  warn "未找到 package.json（尝试目录: $PKG_DIR）"
  warn "请在仓库根目录下运行本向导：bash scripts/npm-publish-wizard.sh"
  exit 1
fi
if [[ "$PKG_DIR" != "." ]]; then
  note "切换到包目录: $PKG_DIR"
  cd "$PKG_DIR"
fi

PKG_NAME="$(node -p "require('./package.json').name" 2>/dev/null || true)"
PKG_VERSION="$(node -p "require('./package.json').version" 2>/dev/null || true)"
PKG_DESC="$(node -p "require('./package.json').description || ''" 2>/dev/null || true)"
PKG_LICENSE="$(node -p "require('./package.json').license || ''" 2>/dev/null || true)"
PKG_MAIN="$(node -p "require('./package.json').main || ''" 2>/dev/null || true)"
PKG_PRIVATE="$(node -p "String(require('./package.json').private)" 2>/dev/null || true)"

if [[ -z "$PKG_NAME" || -z "$PKG_VERSION" ]]; then
  warn "无法读取 package.json 的 name/version"
  exit 1
fi
say "包名: $PKG_NAME"
say "本地版本: $PKG_VERSION"
[[ -n "$PKG_DESC" ]] && say "描述: $PKG_DESC" || warn "description 为空（npm 页面展示需要）"
say "license: ${PKG_LICENSE:-未设置}  main: ${PKG_MAIN:-未设置}  private: $PKG_PRIVATE"
if [[ "$PKG_PRIVATE" == "true" ]]; then
  warn "\"private\": true 的包禁止发布，请先改为 false 或移除该字段"
  exit 1
fi
say ""

# 1c) 官方源包名占用与版本单调性
say "查询官方源占用（显式 --registry，避免镜像延迟）..."
LATEST="$(npm view "$PKG_NAME" version --registry=https://registry.npmjs.org --prefer-online 2>/dev/null || true)"
if [[ -z "$LATEST" ]]; then
  note "官方源未找到 $PKG_NAME（404）→ 全新包名可用"
else
  say "线上 latest: $LATEST"
  # 同版本是否已存在
  if npm view "$PKG_NAME@$PKG_VERSION" version --registry=https://registry.npmjs.org --prefer-online >/dev/null 2>&1; then
    warn "版本 $PKG_VERSION 已在官方源存在（E403/E409），需先 bump version"
    exit 1
  fi
  # 单调性：本地应大于线上 latest（否则发布后 latest 指向旧版本）
  HIGHEST="$(printf "%s\n%s\n" "$LATEST" "$PKG_VERSION" | sort -V | tail -n1)"
  if [[ "$HIGHEST" != "$PKG_VERSION" ]]; then
    warn "本地 $PKG_VERSION 低于线上 latest $LATEST"
    warn "npm 允许发布，但 latest 标签会指向 $PKG_VERSION（看似回退）"
    if ! confirm "仍要继续发布 $PKG_VERSION？"; then exit 0; fi
  else
    say "版本单调性 OK ($PKG_VERSION > $LATEST)"
  fi
fi
say ""

# 1d) 当前 registry 提示
CURRENT_REGISTRY="$(npm config get registry 2>/dev/null || true)"
say "当前 npm registry: $CURRENT_REGISTRY"
if [[ "$CURRENT_REGISTRY" != "https://registry.npmjs.org/" && "$CURRENT_REGISTRY" != "https://registry.npmjs.org" ]]; then
  note "当前源是镜像，发布时将显式 --registry=https://registry.npmjs.org 覆盖"
fi
say ""

# 1e) 打包预览（必跑，不干净禁止发布）
say "打包预览（npm pack --dry-run，前 80 行）："
say "────────────────────────────────────────────────"
if ! npm pack --dry-run 2>&1 | head -n 80; then
  warn "npm pack --dry-run 执行失败"
  exit 1
fi
say "────────────────────────────────────────────────"
note "请人工检查：无 node_modules/.env/.npmrc/密钥/多余文档"
if ! confirm "打包内容看起来干净，继续？"; then exit 0; fi

# ── Stage 2: 登录官方源 ─────────────────────────────────────────────────
stage "2/5 · 登录官方源"
say "官方源登录态检查（与镜像源隔离）..."
WHOAMI="$(npm whoami --registry=https://registry.npmjs.org 2>/dev/null || true)"
if [[ -n "$WHOAMI" ]]; then
  say "已登录官方源，身份: $WHOAMI"
else
  warn "未登录官方源（npm whoami 无输出）"
  say "需完成浏览器授权 + 2FA 登录"
  say ""
  step "本向导将在当前终端执行："
  say "  npm login --auth-type=web --registry=https://registry.npmjs.org"
  say "它会打印授权链接并等待你在浏览器完成登录/2FA"
  note "提示：若在此终端无法弹出浏览器，请改用另一个交互终端手动执行上述命令"
  pause "按回车开始登录…"
  # 直接在前台执行，继承 TTY
  if npm login --auth-type=web --registry=https://registry.npmjs.org; then
    say "login 命令已结束，复检身份…"
  else
    warn "npm login 返回非 0（可能已取消或失败）"
  fi
  WHOAMI2="$(npm whoami --registry=https://registry.npmjs.org 2>/dev/null || true)"
  if [[ -n "$WHOAMI2" ]]; then
    say "已登录官方源，身份: $WHOAMI2"
  else
    warn "仍未登录官方源"
    warn "请在交互终端手动执行："
    say "  npm login --auth-type=web --registry=https://registry.npmjs.org"
    say "  npm whoami --registry=https://registry.npmjs.org  # 应输出用户名"
    if ! confirm "登录完成后再继续？"; then exit 0; fi
    WHOAMI3="$(npm whoami --registry=https://registry.npmjs.org 2>/dev/null || true)"
    if [[ -z "$WHOAMI3" ]]; then
      warn "仍未登录，无法继续发布"
      exit 1
    fi
    say "已登录: $WHOAMI3"
  fi
fi

# ── Stage 3: 发布确认门 ─────────────────────────────────────────────────
stage "3/5 · 发布确认"
say "准备发布: $PKG_NAME@$PKG_VERSION → https://registry.npmjs.org"
say ""
warn "发布即公开；72 小时内可用 npm unpublish 撤回，之后只能 npm deprecate"
note "包主页将为: https://www.npmjs.com/package/$PKG_NAME"
say ""
if ! confirm "确认发布 $PKG_NAME@$PKG_VERSION 到官方源？"; then
  say "已取消发布"
  exit 0
fi

# ── Stage 4: 发布 ───────────────────────────────────────────────────────
stage "4/5 · 发布"
say "执行：npm publish --registry=https://registry.npmjs.org"
say "（不要重定向输出；2FA 账号会打印授权链接，按回车打开浏览器完成审批）"
say ""
# 前台执行，继承 TTY；失败时给出分支指引
if npm publish --registry=https://registry.npmjs.org; then
  say ""
  say "发布命令已返回成功"
else
  EXIT_CODE=$?
  warn "npm publish 失败（exit $EXIT_CODE）"
  say ""
  say "常见报错对照："
  say "  E403/E409 版本重复 → 改 package.json version 后重跑本向导"
  say "  E401/ENEEDAUTH 未登录 → 回到阶段 2 重新登录"
  say "  EOTP 非交互环境 → 必须在交互终端运行本向导，勿重定向输出"
  say "  E403 需 2FA → 按提示完成浏览器审批，或用 --otp=<6位码>"
  exit 1
fi

# ── Stage 5: 验证 ───────────────────────────────────────────────────────
stage "5/5 · 发布后验证"
say "验证线上版本（--prefer-online 跳过本地缓存）..."
REMOTE_VERSION="$(npm view "$PKG_NAME" version --registry=https://registry.npmjs.org --prefer-online 2>/dev/null || true)"
REMOTE_TAGS="$(npm view "$PKG_NAME" dist-tags --registry=https://registry.npmjs.org --prefer-online 2>/dev/null || true)"
say "线上 version: ${REMOTE_VERSION:-（查询失败）}"
say "dist-tags: ${REMOTE_TAGS:-（查询失败）}"
say ""
if [[ "$REMOTE_VERSION" == "$PKG_VERSION" ]]; then
  say "版本一致，发布成功！"
else
  warn "线上 version ($REMOTE_VERSION) 与本地 ($PKG_VERSION) 不一致"
  warn "可能原因：镜像同步延迟或 latest 未更新；稍等后重查："
  say "  npm view $PKG_NAME version --registry=https://registry.npmjs.org --prefer-online"
fi
say ""
say "包主页: https://www.npmjs.com/package/$PKG_NAME"
say "可选：临时目录试装："
say "  mkdir /tmp/npm-verify && cd /tmp/npm-verify && npm install $PKG_NAME --registry=https://registry.npmjs.org"
say ""

finish

